package constants

const BRANCH_LIST_VIEW = "BRANCH_LIST_VIEW"
const COMMIT_LIST_VIEW = "COMMIT_LIST_VIEW"
const FILE_CHANGED_VIEW = "FILE_CHANGED_VIEW"
const MENU_VIEW = "MENU_VIEW"
const HELP_VIEW = "HELP_VIEW"
const DIFF_VIEW = "DIFF_VIEW"

const NEW_BRANCH_POPUP = "NEW_BRANCH_POPUP"
const PUSH_POPUP = "PUSH_POPUP"
const PUll_POPUP = "PUll_POPUP"
const COMMIT_POPUP = "COMMIT_POPUP"

var HIGHLIGHT_VIEW = MENU_VIEW
var LEFT_VIEW = FILE_CHANGED_VIEW
var RIGTH_VIEW = COMMIT_LIST_VIEW
