package constants

const BRANCH_LIST_VIEW = "BRANCH_LIST_VIEW"
const COMMIT_LIST_VIEW = "COMMIT_LIST_VIEW"
const FILE_CHANGED_VIEW = "FILE_CHANGED_VIEW"
const MENU_VIEW = "MENU_VIEW"
const HELP_VIEW = "HELP_VIEW"
const NEW_COMMIT_POPUP = "NEW_COMMIT_POPUP"

var SELECTED_MENU = MENU_VIEW
